### ISSUE TITLE
关于不带标签短信数据

### ISSUE THREAD

**Issue by escyezi** [hrwhisper/SpamMessage#2]
有没有不带标签短信.txt里面对应的标签数据？不然即使判断了结果也没办法知道对错啊……

**Comment by hrwhisper** [comment]
没有这个的标签数据哦。
就相当于不带标签短信是真实环境中的，你能做的就是离线训练模型，对带标签的数据划分训练集和测试集。
如果一定要那个不带标签的短信的类别，可以自行标注...
